var descriptors = {
    1: "dark",
    2: "light",
    3: "bright",
    4: "small",
    5: "large",
    6: "odd",
    7: "round",
    8: "square",
    9: "narrow",
    10: "snowy",
    11: "wet",
    12: "dry",
    13: "noisy",
    14: "urban",
    15: "rural",
    16: "empty",
    17: "elegant",
    18: "sweet",
    19: "cool",
    20: "hot",
    21: "cold",
}

var subjects = {
    1: "street",
    2: "flowers",
    3: "trees",
    4: "vine",
    5: "leaf",
    6: "fields",
    7: "rain",
    8: "water",
    9: "ice",
    10: "steam",
    11: "pathway",
    12: "trail",
    13: "family",
    14: "self portrait",
    15: "someone engaging in a hobby",
    16: "food",
    17: "someone cooking",
    18: "people in love",
    19: "sports",
    20: "clouds",
    21: "sunrise",
    21: "sunset",
    22: "car",
    23: "animals",
    24: "Arrows",
    25: "an arch",
    26: "trash",
    27: "glass",
    28: "puddle",
    29: "leading lines",
    30: "reflection",
    31: "machines",
    32: "paint",
}

export default {subjects, descriptors};